"""Keeps a scrolling list of widget rows hovering the row under the cursor.

**The problem.** Panels built from real `QWidget` rows in a layout (Stats
Day/Week/Month, the Tags list) style their hover with QSS `:hover`, which Qt
drives from enter/leave events generated by mouse MOVEMENT. Scroll the list with
the cursor held still and nothing re-resolves which row is now underneath it:
the highlight stays on the row that was there when the mouse last moved. With
the transport-bar blur running, the panel's hide/show grab cycle re-resolves
hover ~5x/sec instead, so the same defect reads as a highlight that jumps and
blinks between rows rather than one that sticks. Two symptoms, one cause.

**Why the library panel doesn't have it.** `LibraryPanel` is a `QListView` with a
model and a delegate: hover is model state (`BookModel.set_hovered`) fed by
`QListView.entered`, and the view recomputes that as content scrolls. The rows
here are plain widgets with no view to do that, so the recomputation has to be
done explicitly — which is what this class is.

**Why not a wholesale port to model/view.** That would be a rewrite of both
panels rather than a fix, and these rows are genuinely widget-shaped (nested
layouts, per-row covers loaded async, child labels with their own styling).
Matching the *behaviour* — resolve from cursor position, recompute when content
moves — is what actually fixes the bug and is the part that generalizes.

**Designed for keyboard selection to land on top.** The hover row is tracked as
explicit state (`hovered_row`) rather than left implicit in Qt's styling, so a
future keyboard cursor can share one "which row is active" notion instead of
fighting a second, invisible one. `suspend()` exists for exactly that: while
keyboard navigation owns the selection, mouse hover can be switched off without
tearing the tracker down, so the two never render two highlights at once.
"""
from PySide6.QtCore import QObject, QPoint, Qt
from PySide6.QtGui import QCursor

# Minimum real cursor displacement, in pixels, required to reclaim from a
# suspended (keyboard-owned) state — same role as the traveling marker's own
# _KBDNAV_CURSOR_JITTER_PX (app.py): a synthetic Enter/Leave pair from the
# transport-bar blur grab's hide/show cycle (~5-15x/sec while a book plays;
# see this file's own module docstring) reports the SAME cursor position each
# time, so comparing against an anchor rather than reacting to the event's
# mere existence is what tells a real move apart from that artifact.
_MOUSE_RECLAIM_JITTER_PX = 3


class ScrollHoverTracker(QObject):
    """Re-resolves the hovered row of a scroll area whenever its content moves.

    `scroll` is the QScrollArea; `rows_of` is a zero-arg callable returning the
    current row widgets in order. Rows are looked up live rather than cached
    because both panels rebuild their rows wholesale on refresh, and a cached
    list would go stale exactly when the panel repopulates."""

    def __init__(self, scroll, rows_of, parent=None, on_mouse_reclaim=None):
        super().__init__(parent)
        self._scroll = scroll
        self._rows_of = rows_of
        self._hovered = None
        self._suspended = False
        self._suspend_anchor = None  # cursor pos at the moment of suspend(True) — see suspend()
        # Optional zero-arg callback, fired when a REAL mouse event arrives while
        # suspended (added 2026-09-08, for Tags' keyboard cursor) — most-recent-
        # input-wins, the same principle the traveling-marker modality machinery
        # uses elsewhere in this app: whichever device moved last owns the
        # highlight. Without this, suspend(True) was sticky — only an explicit
        # suspend(False) from the keyboard side could ever release it, so real
        # mouse movement while a keyboard cursor was active did nothing at all
        # (reported live: "it broke the mouse hover"). The callback lets the
        # OWNER of the keyboard cursor (which this class knows nothing about)
        # clear its own state in response, instead of this generic tracker
        # reaching into caller-specific concepts it shouldn't know about.
        self._on_mouse_reclaim = on_mouse_reclaim
        scroll.verticalScrollBar().valueChanged.connect(self._resync)
        # Mouse movement is the OTHER half: valueChanged alone would only track
        # while scrolling, so plain hovering would never highlight anything.
        #
        # The filter goes on the QApplication, not the viewport. Rows are
        # children of the scrolled widget, so a move over a row is delivered to
        # the ROW — a viewport-level filter never sees it (verified offscreen:
        # zero moves observed for a move sent to a row).
        #
        # HoverEnter/HoverMove/HoverLeave are watched alongside the mouse events
        # rather than instead of them. A plain QWidget receives MouseMove only
        # while a button is held or it has setMouseTracking(True) — neither is
        # true of these rows — so a button-less move across a row produces no
        # MouseMove at all, and Enter fires once at the boundary. That is why
        # the first version highlighted on scroll but not on plain hover.
        # WA_Hover (set below) makes Qt synthesise the Hover* family, which
        # tracks movement WITHIN a row, so the resync no longer depends on
        # guessing which event Qt happens to send.
        #
        # Every branch is scoped to this scroll area's own descendants, so other
        # panels are unaffected.
        from PySide6.QtWidgets import QApplication
        QApplication.instance().installEventFilter(self)
        # Mouse tracking on the scrolled widget and the viewport, so pixels that
        # belong to the CONTAINER rather than to a row still produce a move.
        #
        # Without this the highlight goes STALE on those pixels instead of
        # clearing or moving: _resync only ever runs from an event, so at a
        # container-owned pixel no row emits anything, nothing recomputes, and
        # whatever row was resolved last stays lit. Observed live at a row
        # boundary — the SAME y lit row 0 when approached from above and row 1
        # when approached from below, which is a stale highlight, not a
        # position-dependent one. A container-owned pixel exists at every row
        # boundary (see TODO.md, the one-pixel hit-test seam), so this is
        # reachable in normal use, not a corner case.
        content = scroll.widget()
        if content is not None:
            content.setMouseTracking(True)
        scroll.viewport().setMouseTracking(True)

    _TRACKED_EVENTS = None  # built lazily; QEvent import is deferred

    def eventFilter(self, obj, event):
        from PySide6.QtCore import QEvent
        if ScrollHoverTracker._TRACKED_EVENTS is None:
            ScrollHoverTracker._TRACKED_EVENTS = frozenset((
                QEvent.Type.Enter, QEvent.Type.Leave, QEvent.Type.MouseMove,
                QEvent.Type.HoverEnter, QEvent.Type.HoverMove,
                QEvent.Type.HoverLeave,
            ))
        if event.type() in ScrollHoverTracker._TRACKED_EVENTS:
            try:
                if self._scroll.isAncestorOf(obj):
                    if self._suspended:
                        self._maybe_reclaim_from_mouse()
                    else:
                        self._resync()
            except (RuntimeError, TypeError):
                # obj may be a non-widget QObject, or a widget already deleted
                # by a refresh — neither is ours to track.
                pass
        return False  # never consume — clicks and wheel must pass through

    @property
    def hovered_row(self):
        """The row currently under the cursor, or None. Explicit state, so a
        future keyboard cursor can coordinate with it rather than guess."""
        return self._hovered

    def resync(self):
        """Force an immediate re-check of what's under the cursor right now.

        Call this after any refresh/rebuild of the row widgets. `_resync` is
        otherwise purely event-driven — it only recomputes in response to a
        genuine Enter/Leave/Hover* boundary crossing (see the eventFilter
        above) — so a rebuild that leaves the cursor already resting INSIDE a
        freshly-built row's geometry produces no such crossing and would
        otherwise never get highlighted until the mouse actually moves.
        Confirmed live 2026-09-13: the Tags list's "<" back button leaves the
        cursor sitting where the button was, and the rebuilt row[0] lands at
        that same screen position — no boundary crossing ever happens for it,
        so it stayed unhighlighted (despite the cursor still showing correctly
        as a pointing hand, which is Qt's own unrelated native hit-testing)
        until some OTHER row was hovered first. Returning to the list via
        Backspace never showed this, because the cursor is typically resting
        somewhere else (e.g. over the detail panel's thumbnail grid) when the
        list reappears, so the next real hover is a genuine crossing."""
        self._resync()

    def suspend(self, suspended: bool = True):
        """Stop (or resume) mouse-hover tracking without tearing down.

        For keyboard navigation: while the keyboard owns the selection, hover
        must not paint a second highlight. Suspending clears the current one.
        Records the cursor's position AT THE MOMENT of suspending as the
        reclaim anchor — see _maybe_reclaim_from_mouse."""
        self._suspended = suspended
        if suspended:
            self._suspend_anchor = QCursor.pos()
            self._set_hovered(None)
        else:
            self._suspend_anchor = None
            self._resync()

    def _maybe_reclaim_from_mouse(self):
        """Most-recent-input-wins: called on every tracked event while suspended.
        A genuinely moved cursor hands hover back to the mouse (and tells the
        keyboard-cursor owner, via `on_mouse_reclaim`, to give up its own
        selection); a cursor still sitting where it was when suspend(True) was
        called is a synthetic event (blur-grab hide/show, a stray Enter/Leave
        from the row rebuild suspend() itself can trigger) and is ignored —
        same anchor-and-jitter shape as the traveling marker's own
        _kbdnav_cursor_anchor/_KBDNAV_CURSOR_JITTER_PX (app.py), not a
        coincidence: both solve "which device actually moved last" against the
        same class of synthetic-event noise."""
        anchor = self._suspend_anchor
        if anchor is None:
            return
        pos = QCursor.pos()
        if (abs(pos.x() - anchor.x()) < _MOUSE_RECLAIM_JITTER_PX
                and abs(pos.y() - anchor.y()) < _MOUSE_RECLAIM_JITTER_PX):
            return
        self._suspended = False
        self._suspend_anchor = None
        if self._on_mouse_reclaim is not None:
            self._on_mouse_reclaim()
        self._resync()

    def _resync(self, *_):
        if self._suspended:
            return
        # Only track while the pointer is actually over the viewport. Without
        # this, scrolling by wheel from elsewhere (or a programmatic scroll on
        # refresh) would light a row under a cursor that is somewhere else
        # entirely. Still clears any stale `_hovered` on the way out — a hide
        # (e.g. the Tags list swapped out for its own detail sub-panel) fires a
        # real Leave that reaches here, and leaving `_hovered` pointing at a
        # row that's about to be deleted-and-rebuilt is what let a later
        # `refresh()` come back with a dangling reference instead of a clean
        # slate (found live 2026-09-13: row[0]'s hover silently no-opped after
        # returning from a tag's detail panel via the "<" button — see
        # `resync()` below for the other half of that fix).
        viewport = self._scroll.viewport()
        if not viewport.isVisible():
            self._hovered = None
            return
        # Enumerate before the containment test, not after: this is what applies
        # WA_Hover, and rows must carry it BEFORE the cursor first arrives or
        # they emit no Hover events for that first entry.
        rows = self._current_rows()
        pos = viewport.mapFromGlobal(QCursor.pos())
        if not viewport.rect().contains(pos):
            self._set_hovered(None)
            return
        self._set_hovered(self._row_at(pos, rows))

    def _current_rows(self):
        """Rows as they are right now, each guaranteed to emit Hover events.

        WA_Hover is applied here rather than at each row's construction so both
        panels get it from one place and a row rebuilt by a refresh can never
        miss it. Qt only synthesises HoverEnter/HoverMove/HoverLeave for widgets
        carrying this attribute, and those are what report movement WITHIN a
        row — without them a button-less move across an already-entered row
        produces no event at all."""
        rows = []
        for row in self._rows_of():
            if row is None:
                continue
            if not row.testAttribute(Qt.WidgetAttribute.WA_Hover):
                row.setAttribute(Qt.WidgetAttribute.WA_Hover, True)
            rows.append(row)
        return rows

    def _row_at(self, viewport_pos: QPoint, rows=None):
        for row in (self._current_rows() if rows is None else rows):
            if not row.isVisible():
                continue
            top_left = row.mapTo(self._scroll.viewport(), QPoint(0, 0))
            if top_left.y() <= viewport_pos.y() < top_left.y() + row.height():
                return row
        return None

    def _set_hovered(self, row):
        if row is self._hovered:
            return
        previous, self._hovered = self._hovered, row
        # Drive the QSS :hover rule through a dynamic property rather than
        # relying on Qt's own hover state, which is what fails to update here.
        # The stylesheet selects on [hovered="true"], so this is the same
        # styling path with a trigger the panel controls.
        for widget, state in ((previous, False), (row, True)):
            if widget is None:
                continue
            widget.setProperty("hovered", "true" if state else "false")
            widget.style().unpolish(widget)
            widget.style().polish(widget)
