"""Keeps a scrolling list of widget rows hovering the row under the cursor.

**The problem.** Panels built from real `QWidget` rows in a layout (Stats
Day/Week/Month, the Tags list) style their hover with QSS `:hover`, which Qt
drives from enter/leave events generated by mouse MOVEMENT. Scroll the list with
the cursor held still and nothing re-resolves which row is now underneath it:
the highlight stays on the row that was there when the mouse last moved. With
the transport-bar blur running, the panel's hide/show grab cycle re-resolves
hover ~5x/sec instead, so the same defect reads as a highlight that jumps and
blinks between rows rather than one that sticks. Two symptoms, one cause.

**Why the library panel doesn't have it.** `LibraryPanel` is a `QListView` with a
model and a delegate: hover is model state (`BookModel.set_hovered`) fed by
`QListView.entered`, and the view recomputes that as content scrolls. The rows
here are plain widgets with no view to do that, so the recomputation has to be
done explicitly — which is what this class is.

**Why not a wholesale port to model/view.** That would be a rewrite of both
panels rather than a fix, and these rows are genuinely widget-shaped (nested
layouts, per-row covers loaded async, child labels with their own styling).
Matching the *behaviour* — resolve from cursor position, recompute when content
moves — is what actually fixes the bug and is the part that generalizes.

**Designed for keyboard selection to land on top.** The hover row is tracked as
explicit state (`hovered_row`) rather than left implicit in Qt's styling, so a
future keyboard cursor can share one "which row is active" notion instead of
fighting a second, invisible one. `suspend()` exists for exactly that: while
keyboard navigation owns the selection, mouse hover can be switched off without
tearing the tracker down, so the two never render two highlights at once.
"""
from PySide6.QtCore import QObject, QPoint, Qt
from PySide6.QtGui import QCursor


class ScrollHoverTracker(QObject):
    """Re-resolves the hovered row of a scroll area whenever its content moves.

    `scroll` is the QScrollArea; `rows_of` is a zero-arg callable returning the
    current row widgets in order. Rows are looked up live rather than cached
    because both panels rebuild their rows wholesale on refresh, and a cached
    list would go stale exactly when the panel repopulates."""

    def __init__(self, scroll, rows_of, parent=None):
        super().__init__(parent)
        self._scroll = scroll
        self._rows_of = rows_of
        self._hovered = None
        self._suspended = False
        scroll.verticalScrollBar().valueChanged.connect(self._resync)
        # Mouse movement is the OTHER half: valueChanged alone would only track
        # while scrolling, so plain hovering would never highlight anything.
        #
        # The filter goes on the QApplication, not the viewport. Rows are
        # children of the scrolled widget, so a move over a row is delivered to
        # the ROW — a viewport-level filter never sees it (verified offscreen:
        # zero moves observed for a move sent to a row).
        #
        # HoverEnter/HoverMove/HoverLeave are watched alongside the mouse events
        # rather than instead of them. A plain QWidget receives MouseMove only
        # while a button is held or it has setMouseTracking(True) — neither is
        # true of these rows — so a button-less move across a row produces no
        # MouseMove at all, and Enter fires once at the boundary. That is why
        # the first version highlighted on scroll but not on plain hover.
        # WA_Hover (set below) makes Qt synthesise the Hover* family, which
        # tracks movement WITHIN a row, so the resync no longer depends on
        # guessing which event Qt happens to send.
        #
        # Every branch is scoped to this scroll area's own descendants, so other
        # panels are unaffected.
        from PySide6.QtWidgets import QApplication
        QApplication.instance().installEventFilter(self)

    _TRACKED_EVENTS = None  # built lazily; QEvent import is deferred

    def eventFilter(self, obj, event):
        from PySide6.QtCore import QEvent
        if ScrollHoverTracker._TRACKED_EVENTS is None:
            ScrollHoverTracker._TRACKED_EVENTS = frozenset((
                QEvent.Type.Enter, QEvent.Type.Leave, QEvent.Type.MouseMove,
                QEvent.Type.HoverEnter, QEvent.Type.HoverMove,
                QEvent.Type.HoverLeave,
            ))
        if event.type() in ScrollHoverTracker._TRACKED_EVENTS:
            try:
                if self._scroll.isAncestorOf(obj):
                    self._resync()
            except (RuntimeError, TypeError):
                # obj may be a non-widget QObject, or a widget already deleted
                # by a refresh — neither is ours to track.
                pass
        return False  # never consume — clicks and wheel must pass through

    @property
    def hovered_row(self):
        """The row currently under the cursor, or None. Explicit state, so a
        future keyboard cursor can coordinate with it rather than guess."""
        return self._hovered

    def suspend(self, suspended: bool = True):
        """Stop (or resume) mouse-hover tracking without tearing down.

        For keyboard navigation: while the keyboard owns the selection, hover
        must not paint a second highlight. Suspending clears the current one."""
        self._suspended = suspended
        if suspended:
            self._set_hovered(None)
        else:
            self._resync()

    def _resync(self, *_):
        if self._suspended:
            return
        # Only track while the pointer is actually over the viewport. Without
        # this, scrolling by wheel from elsewhere (or a programmatic scroll on
        # refresh) would light a row under a cursor that is somewhere else
        # entirely.
        viewport = self._scroll.viewport()
        if not viewport.isVisible():
            return
        # Enumerate before the containment test, not after: this is what applies
        # WA_Hover, and rows must carry it BEFORE the cursor first arrives or
        # they emit no Hover events for that first entry.
        rows = self._current_rows()
        pos = viewport.mapFromGlobal(QCursor.pos())
        if not viewport.rect().contains(pos):
            self._set_hovered(None)
            return
        self._set_hovered(self._row_at(pos, rows))

    def _current_rows(self):
        """Rows as they are right now, each guaranteed to emit Hover events.

        WA_Hover is applied here rather than at each row's construction so both
        panels get it from one place and a row rebuilt by a refresh can never
        miss it. Qt only synthesises HoverEnter/HoverMove/HoverLeave for widgets
        carrying this attribute, and those are what report movement WITHIN a
        row — without them a button-less move across an already-entered row
        produces no event at all."""
        rows = []
        for row in self._rows_of():
            if row is None:
                continue
            if not row.testAttribute(Qt.WidgetAttribute.WA_Hover):
                row.setAttribute(Qt.WidgetAttribute.WA_Hover, True)
            rows.append(row)
        return rows

    def _row_at(self, viewport_pos: QPoint, rows=None):
        for row in (self._current_rows() if rows is None else rows):
            if not row.isVisible():
                continue
            top_left = row.mapTo(self._scroll.viewport(), QPoint(0, 0))
            if top_left.y() <= viewport_pos.y() < top_left.y() + row.height():
                return row
        return None

    def _set_hovered(self, row):
        if row is self._hovered:
            return
        previous, self._hovered = self._hovered, row
        # Drive the QSS :hover rule through a dynamic property rather than
        # relying on Qt's own hover state, which is what fails to update here.
        # The stylesheet selects on [hovered="true"], so this is the same
        # styling path with a trigger the panel controls.
        for widget, state in ((previous, False), (row, True)):
            if widget is None:
                continue
            widget.setProperty("hovered", "true" if state else "false")
            widget.style().unpolish(widget)
            widget.style().polish(widget)
