BOOK_QUOTES = [
    ("DON'T PANIC", "A Hitchhiker's Guide to the Galaxy", 36, 14, "red", "center"),
    ("The man in black fled across the desert, and the gunslinger followed.", "The Gunslinger", 18, 14, "white", "right"),
    ("Joffrey<br>Meryn Trant<br>Illyn Payne<br>The Hound<br>The Mountain<br>Tywin Lannister<br>Walder Frey", "A Game of Thrones", 15, 14, "white", "center"),
    ("The sky above the port was the color of television, tuned to a dead channel.", "Neuromancer", 22, 14, "white", "right"),
    ("A screaming comes across the sky.", "Gravity's Rainbow", 19, 14, "white", "center"),
    ("Body found floating by the docks...", "The Blade Itself", 19, 14, "white", "center"),
    ("Never trust a man who carries a handkerchief, I always say. One of many prejudicial rules of thumb.", "Hard-Boiled Wonderland and the End of the World", 18, 13, "white", "right"),
    ("I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration. I will face my fear. I will permit it to pass over me and through me. And when it has gone past I will turn the inner eye to see its path. Where the fear has gone there will be nothing. Only I will remain.", "Dune", 15, 14, "white", "right"),
    ("Last night I dreamt I went to Manderley again.", "Rebecca", 22, 14, "white", "center"),
    ("It was ever thus.", "Memories of Ice", 24, 14, "white", "center"),
    ("And the sea, my friends,<br>does not dream of you.", "Reaper's Gale", 22, 14, "white", "right"),
    ("Thunder rolled... It rolled a six.", "Guards! Guards!", 20, 14, "white", "center"),
    ("Caddy smelled like trees.", "The Sound and the Fury", 24, 14, "white", "right"),
    ("So that is marriage, Lily thought, a man and a woman looking at a girl throwing a ball.", "To the Lighthouse", 20, 14, "white", "right"),
    ("I'm rambling. I really like you. You make me want to talk. I don't know what time it is.", "Leaving Las Vegas", 18, 14, "white", "right"),
    ("There are no wrong turnings. Only paths we had not known we were meant to walk.", "Tigana", 20, 14, "white", "right"),
    ("Apártense, vacas, que la vida es corta.", "Cien años de soledad", 24, 14, "white", "right"),
    ("Why am I always looking at life through a window?", "Flowers for Algernon", 22, 14, "white", "right"),
    ("- Cubitum eamus?<br>- What?<br>- Nothing.", "The Secret History", 20, 14, "white", "right"),
    ("I often wonder what I'd do if there weren't any books in the world.", "Giovanni's Room", 19, 14, "white", "right"),
    ("REⱭЯUM", "The Shining", 38, 14, "red", "center"),
    ("Call me Ishmael.", "Moby-Dick; or, The Whale", 24, 14, "white", "center"),
    ("It was the best of times, it was the worst of times...", "A Tale of Two Cities", 20, 14, "white", "right"),
    ("Violence is the last refuge of the incompetent.", "Foundation", 22, 14, "white", "right"),
    ("This has been a novel about some people who were punished entirely too much for what they did... If there was any 'sin,' it was that these people wanted to keep on having a good time forever, and were punished for that, but, as I say, I feel that, if so, the punishment was far too great.", "A Scanner Darkly", 15, 14, "white", "right"),
    ("Give a man a fire and he's warm for a day, but set fire to him and he's warm for the rest of his life.", "Jingo", 20, 14, "white", "right"),
    ("You have to be realistic about these things.", "The Blade Itself", 22, 14, "white", "center"),
    ("May the days be aimless. Let the seasons drift. Do not advance the action according to a plan." "White Noise", 22, 14, "white", "right"),
    ("I do things like get in a taxi and say, \"The library, and step on it.\"", "Infinite Jest", 19, 14, "white", "right"),
]
